#!/usr/bin/env bash


set -eu


IMAGE="schedule"
OUTPORT=8000
ENVFILE=".env"
LOCAL_DB="./data"
CONTAINER_DB="/app/data"
NAME="schedule"


cmd_build() {
	docker build -t "$IMAGE" .
}

cmd_collectstatic() {
	docker run \
        --rm \
        --env-file "$ENVFILE" \
        -v "${LOCAL_DB}:${CONTAINER_DB}" \
        --name "${NAME}_static" \
        --entrypoint ./manage.py \
        "$IMAGE" collectstatic --noinput
}

cmd_migrate() {
	docker run \
        --rm \
        --env-file "$ENVFILE" \
        -v "${LOCAL_DB}:${CONTAINER_DB}" \
        --name "${NAME}_migrate" \
        --entrypoint ./manage.py \
        "$IMAGE" migrate
}

cmd_all_build() {
    cmd_build
    cmd_collectstatic
    cmd_migrate
}

cmd_run() {
    local -r proc_count="$1"
	docker run \
        --env-file "$ENVFILE" \
        -p "${OUTPORT}:80" \
        -v "${LOCAL_DB}:${CONTAINER_DB}" \
        --name "$NAME" \
        "$IMAGE" "$proc_count"
}

cmd_rund() {
    local -r proc_count="$1"
	docker run \
        -d \
        --restart=always \
        --env-file "$ENVFILE" \
        -p "${OUTPORT}:80" \
        -v "${LOCAL_DB}:${CONTAINER_DB}" \
        --name "$NAME" \
        "$IMAGE" "$proc_count"
}

cmd_stop() {
    docker stop "$NAME"
}

cmd_rm() {
    docker rm "$NAME"
}

cmd_clean() {
    docker rmi "$IMAGE"
}

cmd_createsuperuser() {
    docker run \
        --rm \
        -it \
        --env-file "$ENVFILE" \
        -v "${LOCAL_DB}:${CONTAINER_DB}" \
        --name "${NAME}_superuser" \
        --entrypoint ./manage.py \
        "$IMAGE" createsuperuser
}

cmd_pull_rebuild_and_restart() {
    git pull && \
        cmd_build && \
        cmd_stop && \
        cmd_rm && \
        cmd_rund 2
}


case "$1" in
    static) shift;          cmd_collectstatic    ;;
    build) shift;           cmd_all_build        ;;
    run) shift;             cmd_run "$@"         ;;
    rund) shift;            cmd_rund "$@"        ;;
    stop) shift;            cmd_stop             ;;
    rm) shift;              cmd_rm               ;;
    clean) shift;           cmd_clean            ;;
    createsuperuser) shift; cmd_createsuperuser  ;;
    rebuild) shift;         cmd_pull_rebuild_and_restart  ;;

    *) cmd_run "$@" ;;
esac
exit 0