# Generated by Django 5.1.1 on 2024-10-05 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('schedule', '0001_initial'),
        ('schedule', '0002_rename__class_exercise_auditory_and_more'),
        ('schedule', '0003_alter_exercise_is_even'),
        ('schedule', '0004_remove_exercise_is_even_exercise_parity'),
        ('schedule', '0005_alter_exercise_time_start'),
        ('schedule', '0006_alter_exercise_weekday'),
        ('schedule', '0007_classgroup'),
        ('schedule', '0008_exercise_group'),
        ('schedule', '0009_alter_classgroup_name'),
        ('schedule', '0010_alter_exercise_weekday')
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(
                    choices=[
                        (0, 'Понедельник'),
                        (1, 'Вторник'),
                        (2, 'Среда'),
                        (3, 'Четверг'),
                        (4, 'Пятница'),
                        (5, 'Суббота'),
                        (6, 'Воскресенье')
                    ],
                    validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(6)
                    ]
                )),
                ('name', models.CharField(max_length=80)),
                ('time_start', models.TimeField()),
                ('teacher', models.CharField(max_length=80)),
                ('auditory', models.CharField(max_length=20)),
                ('parity', models.CharField(
                    choices=[
                        ('EVE', 'Чет'),
                        ('ODD', 'Нечет'),
                        ('COM', 'Общее')
                    ],
                    default='COM',
                    max_length=3
                )),
                ('group', models.ForeignKey(
                    default=1,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='schedule.classgroup'
                )),
            ],
        ),
    ]
