# Generated by Django 5.1.1 on 2024-09-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='_class',
            new_name='auditory',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='is_odd',
            new_name='is_even',
        ),
    ]
