# Generated by Django 5.1.1 on 2024-09-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_exercise_is_even_exercise_parity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
