# Generated by Django 5.1.1 on 2024-09-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_classgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='schedule.classgroup'),
            preserve_default=False,
        ),
    ]
