# Generated by Django 5.1.1 on 2024-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_exercise_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
