# Generated by Django 5.1.1 on 2024-09-09 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=80)),
                ('time_start', models.CharField(max_length=40)),
                ('teacher', models.CharField(max_length=80)),
                ('_class', models.CharField(max_length=20)),
                ('is_odd', models.BooleanField()),
            ],
        ),
    ]
