# Generated by Django 5.1.1 on 2024-09-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_rename__class_exercise_auditory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='is_even',
            field=models.BooleanField(default=None),
        ),
    ]
