# Generated by Django 5.1.1 on 2024-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_exercise_is_even'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='is_even',
        ),
        migrations.AddField(
            model_name='exercise',
            name='parity',
            field=models.CharField(choices=[('EVE', 'Чет'), ('ODD', 'Нечет'), ('COM', 'Общее')], default='COM', max_length=3),
        ),
    ]
